# Scrape city data in numbeo.com
mainURL <- "https://www.timeanddate.com/weather/poland/warsaw/climate"
cat("\n"); cat(mainURL);cat("\n")
mainSource <- GET(mainURL, ssl.verifypeer = FALSE)
mainSource <- read_html(mainURL)

# Run js script that run nested js in html to get generated by it data
system("D:/programs/phantomjs-2.1.1-windows/bin/phantomjs.exe D:/analytics/shiny/nomad_life/scraper_timeanddate.js")

# File weather.htlm is the effect of phantomjs cmd run, refer to that file for more
sourceJS <- xml2::read_html("D:/analytics/shiny/nomad_life/data/weather.html")

# Nodes are ready for extraction
tMaxNodes <- sourceJS %>% html_nodes(".climategraph__high-label")
sapply(tMaxNodes, html_text)

# TODO MORE SCRAPING FROM THAT WEB
# ...


